version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: blog
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5435:5432'
    restart: unless-stopped
volumes:
  postgres: